services: 
  rfxcom2mqtt:
    image: sguernion/rfxcom2mqtt:1.0.0-dev
    #command: ["ls", "./dist/application"]
    build: ./
    volumes:
      - ./apps/backend/config:/app/data
    ports:
      - 8070:8891  # Single port for both frontend (/) and backend (/api)
    #devices:
    #  - /dev/ttyUSB1:/dev/ttyUSB0
    environment:
      - TZ=Europe/Paris
      - NODE_ENV=production
      - PROFILE=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8891/api/bridge/info"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
