import React from 'react';
import { Box, Typography, useTheme, alpha } from '@mui/material';
import { Article as ArticleIcon } from '@mui/icons-material';

function CustomNoRowsOverlay() {
  const theme = useTheme();

  return (
    <Box
      sx={{
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        height: '100%',
        py: 4,
        color: 'text.secondary',
      }}
    >
      <Box
        sx={{
          p: 3,
          borderRadius: '50%',
          backgroundColor: alpha(theme.palette.primary.main, 0.1),
          mb: 2,
        }}
      >
        <ArticleIcon
          sx={{
            fontSize: 48,
            color: alpha(theme.palette.primary.main, 0.6),
          }}
        />
      </Box>

      <Typography variant="h6" gutterBottom fontWeight="medium">
        No Log Messages
      </Typography>

      <Typography variant="body2" color="text.secondary" textAlign="center" sx={{ maxWidth: 300 }}>
        No log messages are currently available. Messages will appear here as they are generated by
        the system.
      </Typography>

      <Box sx={{ mt: 2 }}>
        <Typography variant="caption" color="text.secondary">
          Try refreshing or check your connection status
        </Typography>
      </Box>
    </Box>
  );
}

export default CustomNoRowsOverlay;
